### ISSUE TITLE
Some quirks in the Install docs

### ISSUE THREAD

**Issue by Tecnologic** [heinemannj/huawei_solar_hems#1]
Hi,

thanks for ur work.

is the install there is a section mentioning: 
homeassistant:
  customize_glob: !include customize_glob.yaml
  customize: !include customize.yaml

where can these files be found?

For the dasboards i get this error:
![image](https://github.com/user-attachments/assets/c27bdc91-fe8d-4dbf-8679-4c200b994c91)
layout-card is installed. Am i missing somthing else?

Tnaks

**Comment by heinemannj** [comment]
a) For the moment not used by PV dashboards. You can comment out below lines or upload the both files I've uploaded this morning:

```
customize_glob: !include customize_glob.yaml
customize: !include customize.yaml
```

b) Have you restarted your Home Assistant?

If yes try the following:

Modify `dashboards/420-pv/views/421-pv.yaml`:

```
title: 421-PV
theme: dashboards
path: 421-pv
icon: mdi:solar-power-variant
type: custom:layout-card
layout_type: custom:grid-layout
badges: []
```

Restart HA afterwards.

**Comment by Tecnologic** [comment]
Hi ,

Thanks for the answer,

I think my main issue is that emhass is not working. I thought the config is in Ur package yaml but all the entities from there are un available. Huawei solar, epex and solcast are working. I used them before but emhass is missing the config. 

do U know where the emhass_config.yaml is located? I don't find it in the config folder.

**Comment by Tecnologic** [comment]
Rtfm dry my fault. I missed the docs about emhass setup
